version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:80
      - 8091:443
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
          - 1433
    
    environment:
      SA_PASSWORD: "Qwert1234="
      ACCEPT_EULA: "Y"